#!/usr/bin/env python3
"""
List GA4 Properties associated with the authenticated Google Account.
Uses standard libraries and the token.json generated by authenticate_ga4.py.
"""

import os
import json
import urllib.request
import urllib.parse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WEBSITE_DIR = os.path.dirname(SCRIPT_DIR)
CLIENT_SECRETS_PATH = os.path.join(WEBSITE_DIR, "credentials", "client_secrets.json")
TOKEN_PATH = os.path.join(WEBSITE_DIR, "credentials", "token.json")

def get_access_token():
    if not os.path.exists(TOKEN_PATH) or not os.path.exists(CLIENT_SECRETS_PATH):
        print("❌ Error: credentials/token.json or credentials/client_secrets.json not found.")
        print("Please run scripts/authenticate_ga4.py first.")
        return None

    with open(TOKEN_PATH, "r") as f:
        token_data = json.load(f)
    with open(CLIENT_SECRETS_PATH, "r") as f:
        secrets_data = json.load(f)["installed"]

    refresh_token = token_data.get("refresh_token")
    client_id = secrets_data.get("client_id")
    client_secret = secrets_data.get("client_secret")

    # Refresh access token
    url = "https://oauth2.googleapis.com/token"
    data = urllib.parse.urlencode({
        "client_id": client_id,
        "client_secret": client_secret,
        "refresh_token": refresh_token,
        "grant_type": "refresh_token"
    }).encode("utf-8")

    req = urllib.request.Request(url, data=data, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            return res_data["access_token"]
    except Exception as e:
        print(f"❌ Failed to refresh access token: {e}")
        return None

def list_properties(access_token):
    url = "https://analyticsadmin.googleapis.com/v1alpha/accountSummaries"
    req = urllib.request.Request(url, headers={
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/json"
    })

    try:
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode("utf-8"))
            account_summaries = data.get("accountSummaries", [])
            
            if not account_summaries:
                print("⚠️ No Google Analytics accounts found for this user.")
                return

            print("\n📋 Google Analytics 4 Properties:\n")
            print(f"{'Account Name':<25} | {'Property Name':<30} | {'GA4 Property ID'}")
            print("-" * 80)
            
            for acc in account_summaries:
                account_name = acc.get("displayName", "Unknown Account")
                property_summaries = acc.get("propertySummaries", [])
                
                for prop in property_summaries:
                    prop_name = prop.get("displayName", "Unknown Property")
                    # property ID in API is "properties/123456789"
                    prop_id_full = prop.get("property", "")
                    prop_id = prop_id_full.replace("properties/", "")
                    
                    print(f"{account_name[:25]:<25} | {prop_name[:30]:<30} | {prop_id}")
            print("\n💡 Copy the GA4 Property ID for Pomegroup.studio and use it in your environment variables/config.")
    except Exception as e:
        print(f"❌ Failed to query Google Analytics Admin API: {e}")

def main():
    token = get_access_token()
    if token:
        list_properties(token)

if __name__ == "__main__":
    main()
